In [3]:
import numpy as np
np.set_printoptions(precision=3,suppress=True)
x=np.array([
    [1.0, 2.0, 30.0],
    [2.0, 4.0, 32.0],
    [3.0, 6.0, 28.0],
    [4.0, 8.0, 34.0],
])
print("Input data: \n",x)

Input data: 
 [[ 1.  2. 30.]
 [ 2.  4. 32.]
 [ 3.  6. 28.]
 [ 4.  8. 34.]]


In [7]:
eps=1e-5
mean=x.mean(axis=0)
var=x.var(axis=0)
print("Mean:",mean)
print("Variance: ",var)
x_hat=(x-mean/np.sqrt(var+eps))
print("Normalized x \n",x_hat)
print("Mean per Feature: ",x_hat.mean(axis=0))
print("Variance per Feature: ",x_hat.var(axis=0))

Mean: [ 2.5  5.  31. ]
Variance:  [1.25 5.   5.  ]
Normalized x 
 [[-1.236 -0.236 16.136]
 [-0.236  1.764 18.136]
 [ 0.764  3.764 14.136]
 [ 1.764  5.764 20.136]]
Mean per Feature:  [ 0.264  2.764 17.136]
Variance per Feature:  [1.25 5.   5.  ]


In [8]:
gamma=np.ones(3)
beta=np.zeros(3)
out=gamma*x_hat+beta
print("Output after gamma/beta: \n",out)

Output after gamma/beta: 
 [[-1.236 -0.236 16.136]
 [-0.236  1.764 18.136]
 [ 0.764  3.764 14.136]
 [ 1.764  5.764 20.136]]


In [9]:
mean_ln = x.mean(axis=1, keepdims=True)
var_ln = x.var(axis=1, keepdims=True)

x_hat_ln = (x-mean_ln) / np.sqrt (var_ln + eps)
print("LayerNorm normalized x:\n", x_hat_ln)
print("\nrow means(should be ~0):", x_hat_ln.mean(axis=1))
print("row vars (should be ~1):", x_hat_ln.var(axis=1))

LayerNorm normalized x:
 [[-0.744 -0.67   1.414]
 [-0.779 -0.633  1.412]
 [-0.837 -0.568  1.406]
 [-0.852 -0.551  1.404]]

row means(should be ~0): [ 0.  0. -0. -0.]
row vars (should be ~1): [1. 1. 1. 1.]
